controller_list:
  - name: fake_manipulator_controller
    joints:
      - base_roll
      - shoulder_pitch
      - elbow_pitch
      - elbow_roll
      - wrist_pitch
      - wrist_roll
  - name: fake_endeffector_controller
    joints:
      []
